import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'providers/item_providers.dart';
import 'providers/wear_day_providers.dart';
import 'providers/sort_providers.dart';
import 'services/nfc_foreground_service.dart';

// Generated by flutter gen-l10n
import 'package:raw_denim_tracker/l10n/app_localizations.dart';
export 'package:raw_denim_tracker/l10n/app_localizations.dart';

class RawDenimApp extends ConsumerStatefulWidget {
  const RawDenimApp({super.key});

  @override
  ConsumerState<RawDenimApp> createState() => _RawDenimAppState();
}

class _RawDenimAppState extends ConsumerState<RawDenimApp>
    with WidgetsBindingObserver {
  static const _nfcChannel = MethodChannel('app.rawdenim.tracker/nfc');

  final _scaffoldMessengerKey = GlobalKey<ScaffoldMessengerState>();

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _initNfcChannel();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  Future<void> _initNfcChannel() async {
    _nfcChannel.setMethodCallHandler((call) async {
      if (call.method == 'onNfcUri') {
        await _handleNfcUri(call.arguments as String);
      }
    });
    try {
      final initialUri =
          await _nfcChannel.invokeMethod<String>('getInitialNfcUri');
      if (initialUri != null) await _handleNfcUri(initialUri);
    } catch (_) {}
  }

  Future<void> _handleNfcUri(String uri) async {
    final match = RegExp(r'^rawdenim://wear/(.+)$').firstMatch(uri);
    if (match == null) return;
    final itemId = match.group(1)!;

    final item = await ref.read(itemRepositoryProvider).getById(itemId);
    if (item == null || !mounted) return;

    final now = DateTime.now();
    final inserted = await ref.read(wearDayActionsProvider).addWearDay(
          itemId,
          DateTime(now.year, now.month, now.day),
        );
    if (!mounted) return;

    final l10n = AppLocalizations.of(context)!;
    final name = '${item.brand} ${item.model}';
    final message =
        inserted ? l10n.nfcWearDayAdded(name) : l10n.nfcAlreadyWornToday(name);
    _scaffoldMessengerKey.currentState?.showSnackBar(
      SnackBar(content: Text(message), duration: const Duration(seconds: 3)),
    );
  }

  /// When the app returns to the foreground, the native widget receiver may
  /// have written wear days directly to SQLite. Invalidate cached providers
  /// so the UI reflects the latest data without a force-close.
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      ref.invalidate(itemsProvider);
      ref.invalidate(wearDayCountProvider);
      ref.invalidate(sortedItemsProvider);
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Raw Denim Tracker',
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.system,
      routerConfig: appRouter,
      scaffoldMessengerKey: _scaffoldMessengerKey,
      // Wrap every page in NfcForegroundListener so NFC tags are processed
      // app-wide whenever the app is in the foreground.
      builder: (context, child) =>
          NfcForegroundListener(child: child ?? const SizedBox.shrink()),
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
        Locale('de'),
      ],
    );
  }
}
